### ISSUE TITLE
匹配逻辑建议

### ISSUE THREAD

**Issue by jing2si** [uTools-Labs/utools-tpl-bookmarks-search#2]
例如：我的书签标题是: **utools 快速启动 软件**

* 搜索 **utools 快速启动** 可以搜索到
* 搜索 **utools 软件** 搜索不到

* 搜索 **快速启动 软件** 可以搜索到
* 搜索 **软件 快速启动** 搜索不到

也是说必须保持文字顺序一致才能搜索，这样很不方便，因为书签多了，不可能按顺序记住的
原来用 Alfred 就可以，才开始试用的 HapiGo 也可以，谷歌浏览器自带的书签搜索就更强大了

> 这里我只是举例子哈，实际情况搜索 **utools** 就出来了， 我的书签有好几千个，每个标题里我都写的关键字，有点类似火狐的 tag，我想到啥，直接输入关键字就能出来，不用保持他的顺序

书签搜索是我用的比较频繁的功能，很喜欢 utools 这款快速启动工具，目前用起来就这个功能有些小瑕疵。
之前给你们提了一个关机二次确认的功能，你们很快修改了，效率杠杠滴😁

社区里另一个[非官方的书签搜索](https://github.com/LanyuanXiaoyao-Studio/utools-recent-projects)我用了，也是同样的问题

**Comment by jing2si** [comment]
贴几张图对比下
### Chrome 自带搜索
![image](https://user-images.githubusercontent.com/2288824/144619358-49157173-120a-4c2d-819b-bb870f67e319.png)

### utools
![image](https://user-images.githubusercontent.com/2288824/144620240-09fc8a76-d067-4bfd-9a2d-5c905dbf79ef.png)


### HapiGo
![image](https://user-images.githubusercontent.com/2288824/144620163-0acf1ee8-9347-43be-9a98-a63fd47b9c95.png)


Alfred 卸载了，之前一直用，也是可以匹配到的。

**Comment by jing2si** [comment]
**书签与历史记录**插件的作者给我回复了他那[不能实现的原因](https://github.com/LanyuanXiaoyao-Studio/utools-recent-projects/issues/2#issuecomment-985583455)，是不是同样的原因呀😁

**Comment by jing2si** [comment]
创建了一个PR修复了这个问题
![image](https://user-images.githubusercontent.com/2288824/144655330-0cd8fdb2-52ad-4577-9e9b-1a18001735e5.png)

**Comment by uTools-Labs** [comment]
搜索已优化
